shell /usr/bin/zsh

cursor_shape block

url_style curly

remember_window_size no
initial_window_width 640
initial_window_height 480
window_padding_width 30
cursor_blink_interval 0

background_image ~/.config/kitty/output.png
background_image_layout scaled
background_tint 0.97

background_opacity 0.9

font_family Monaspace Neon
font_size 10

cursor_trail 1 

scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
confirm_os_window_close 0

wheel_scroll_multiplier 1.0
touch_scroll_multiplier 1.0

open_url_with firefox

sync_to_monitor no


# BEGIN_KITTY_THEME
# Noctalia
include themes/wallust-colors.conf
# END_KITTY_THEME
