# wallust v3.4
#
# You can copy this file to ~/.config/wallust/wallust.toml (keep in mind is a sample config)

# SIMPLE TUTORIAL, or `man wallust.5`:
# https://explosion-mental.codeberg.page/wallust/
#
# If comming from v2: https://explosion-mental.codeberg.page/wallust/v3.html#wallusttoml

# Global section - values below can be overwritten by command line flags

# How the image is parse, in order to get the colors:
# full - resized - wal - thumb -  fastresize - kmeans
backend = "wal"

# What color space to use to produce and select the most prominent colors:
# lab - labmixed - lch - lchmixed
color_space = "lab"

# Use the most prominent colors in a way that makes sense, a scheme color palette:
# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
palette = "dark16"

# Ensures a "readable contrast" (OPTIONAL, disabled by default)
# Should only be enabled when you notice an unreadable contrast frequently happening
# with your images. The reference color for the contrast is the background color.
check_contrast = true

# Color saturation, between [1% and 100%] (OPTIONAL, disabled by default)
# usually something higher than 50 increases the saturation and below
# decreases it (on a scheme with strong and vivid colors)
saturation = 35

# Alpha value for templating, by default 100 (no other use whatsoever)
alpha = 100

#Threshold
# 1	Not Perceptible by human eyes.
# 1 - 2	Perceptible through close observation.
# 2 - 10	Perceptible at a glance.
# 11 - 49	Colors are more similar than opposite.
# 100	Colors are exact opposite.
threshold = 12

[templates]
# NOTE: prefer '' over "" for paths, avoids escaping.
# template: A RELATIVE path that points to `~/.config/wallust/template` (depends on platform)
# target: ABSOLUTE path in which to place a file with generated templated values.
# ¡ If either one is a directory, then both SHOULD be one. !
# zathura = { template = 'zathura', target = '~/.config/zathura/zathurarc' }

kitty = { template = 'kitty-colors.conf', target = '~/.config/kitty/themes/wallust-colors.conf' }
rofi = { template = 'rofi-colors.conf', target = '~/.config/rofi/wallust-colors.rasi' }
waybar = { template = 'waybar-colors.conf', target = '~/.config/waybar/style/wallust-colors.css'}
colors_module = { template = 'ascii-colors.conf', target = "~/.config/waybar/colors-module" }
hyprlua = { template = 'hypr-lua.conf', target = '~/.config/hypr/configs/wallust-hypr.lua' }
hypr = { template = 'hypr-colors.conf', target = '~/.config/hypr/configs/wallust-hypr.conf' }
vscodium = { template = 'vscode-colors.conf', target = "~/.vscode-oss/extensions/noctalia.noctaliatheme-0.0.5-universal/themes/MyTheme-color-theme.json" }
bash = { template = 'bash-colors.sh', target = "~/.colors.sh"}
zed = { template = 'zed-colors.json', target = "~/.config/zed/themes/wallust.json"}
obsidian = { template = 'obs-colors.css', target = "~/docs/42C3-VLT/.obsidian/themes/Wallust/theme.css"}
firefox = {template = 'fox-colors.css', target = "~/.config/mozilla/firefox/f2oim4s5.default-release/chrome/userChrome.css"}
