source = ~/.config/hypr/configs/wallust-hypr.conf

$font = 911 Porscha Bold Italic
$TIME = cmd[update:1000] date +"%H:%M"

# GENERAL
general {
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  path = /tmp/current_wallpaper.jpg
  blur_passes = 3
  color = rbga($fg)
  crossfade_time = 100.0
  brightness = 0.8
  vibarncy = 2.0
  contrats = 2.0
}

image {
  monitor =
  rotate= 0
  path = /tmp/current_wallpaper.jpg
  size = 800
  rounding = 0
  border_size = 5
  border_color = rgba($color6)
  shadow_passes = 4
  shadow_size = 5
  shadow_color = rgb(15, 0, 20)
  shadow_boost = 1.2
}

image {
  path = ~/Pictures/sonicthumbs.png
  size = 200
  zindex = 6
  position = 300, -170
  border_size = 0
}

image {
  path = ~/Pictures/sonic_clrd.png
  size = 200
  zindex = 5
  position = 290, -175
  border_size = 0
}

shape {
  rotate = 1
  monitor = 
  size = 900, 70
  rounding = 0
  position = 0,150
  color = rgba($color6)
  zindex = 2
  halign = center
  valign = center

  shadow_passes = 2
  shadow_sizle = 2
  shadow_color = rgba($color6)
  shadow_boost = 0.0
}

shape {
  rotate = 0
  monitor =
  size = 1100, 100
  position= 0,-5
  color = rgba($color6)
  zindex = 2
  halign = center
  walign = center 
}

# TIME
label {
  monitor =
  text = $TIME
  color = rgba($fg)
  font_size = 120
  font_family = Crude
  position = 0, 200
  zindex = 10
  halign = center
  valign = center
}

label {
  monitor =
  text = SEGA
  color = rgba($fg)
  font_size = 50
  font_family = SEGA LOGO FONT
  position = 0, -150
  zindex = 4
  halign = center
  valign = center

  shadow_passes = 3
  shadow_size = 5
  shadow_color = rgb(15, 0, 20)
  shadow_boost = 1.5
}

label {
  monitor =
  text = Bilalium
  color = rgba($color6)
  font_size = 60
  font_family = Autography
  position = 0, -200
  zindex = 4
  halign = center
  valign = center
}

label {
  monitor =
  text = BE RIGHT BACK!
  color = rgba($fg)
  font_size = 100
  font_family = Upheaval TT (BRK)
  position = 0, 0
  zindex = 4
  halign = center
  valign = center
}


label {
  monitor = 0
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 50
  font_family = Crude
  position = -30, -300
  halign = center
  valign = center
}

# FINGERPRINT
{
  monitor = "";
  text = "$FPRINTPROMPT";
  color = "$text";
  font_size = 14;
  font_family = $font;
  position = "0, -107";
  halign = "center";
  valign = "center";
}

# USER AVATAR
image {
  path = $HOME/.face
  size = 0
  border_color = $accent
  position = 0, 200
  halign = center
  valign = center
  shadow_passes = 2
  shadow_color = rgb(15,0,20)
  shadow_size = 5
  shadow_boost = 1.2
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 0
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = rgba($color6)
  inner_color = rgba($color6)
  font_family = 911 Porscha
  font_color = rgba($fg)
  fade_on_empty = true
  placeholder_text = B//
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = rgba($color1)
  position = 0, -400
  halign = center
  valign = center
}
