color0 #03043a
color1 #fd4663
color2 #4d50ff
color3 #9533ff
color4 #fc33ff
color5 #8082ff
color6 #bd80ff
color7 #f2f2f3
color8 #5d5d71
color9 #fd4663
color10 #4d50ff
color11 #9533ff
color12 #fc33ff
color13 #8082ff
color14 #bd80ff
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #03043a
background            #03043a
foreground            #f2f2f3
selection_foreground  #afafb6
selection_background  #080949
active_border_color   #4d50ff
inactive_border_color #080949
url_color             #4d50ff

active_tab_foreground   #181925
active_tab_background   #4d50ff
inactive_tab_foreground #afafb6
inactive_tab_background #080949
cursor_trail_color      #afafb6
